/**
 * Hardcoded company lists per ATS, live-verified against each API
 * (checked for a 200 response with a non-empty `jobs` array as of 2026-09-07).
 * Board slugs occasionally change or go quiet — re-verify periodically.
 */
export interface CompanyConfig {
  slug: string;
  name: string;
  domain: string; // used to fetch a logo via Clearbit's logo API
}

export const GREENHOUSE_COMPANIES: CompanyConfig[] = [
  { slug: "stripe", name: "Stripe", domain: "stripe.com" },
  { slug: "airbnb", name: "Airbnb", domain: "airbnb.com" },
  { slug: "coinbase", name: "Coinbase", domain: "coinbase.com" },
  { slug: "pinterest", name: "Pinterest", domain: "pinterest.com" },
  { slug: "lyft", name: "Lyft", domain: "lyft.com" },
  { slug: "reddit", name: "Reddit", domain: "reddit.com" },
  { slug: "databricks", name: "Databricks", domain: "databricks.com" },
  { slug: "gitlab", name: "GitLab", domain: "gitlab.com" },
  { slug: "asana", name: "Asana", domain: "asana.com" },
  { slug: "squarespace", name: "Squarespace", domain: "squarespace.com" },
  { slug: "affirm", name: "Affirm", domain: "affirm.com" },
  { slug: "instacart", name: "Instacart", domain: "instacart.com" },
  { slug: "discord", name: "Discord", domain: "discord.com" },
  { slug: "flexport", name: "Flexport", domain: "flexport.com" },
  { slug: "brex", name: "Brex", domain: "brex.com" },
  { slug: "gusto", name: "Gusto", domain: "gusto.com" },
  { slug: "webflow", name: "Webflow", domain: "webflow.com" },
  { slug: "roblox", name: "Roblox", domain: "roblox.com" },
  { slug: "cloudflare", name: "Cloudflare", domain: "cloudflare.com" },
  { slug: "duolingo", name: "Duolingo", domain: "duolingo.com" },
  { slug: "scaleai", name: "Scale AI", domain: "scale.com" },
  { slug: "checkr", name: "Checkr", domain: "checkr.com" },
  { slug: "figma", name: "Figma", domain: "figma.com" },
  { slug: "robinhood", name: "Robinhood", domain: "robinhood.com" },
  { slug: "twitch", name: "Twitch", domain: "twitch.tv" },
  { slug: "mixpanel", name: "Mixpanel", domain: "mixpanel.com" },
  { slug: "vercel", name: "Vercel", domain: "vercel.com" },
  { slug: "okta", name: "Okta", domain: "okta.com" },
  { slug: "twilio", name: "Twilio", domain: "twilio.com" },
  { slug: "dropbox", name: "Dropbox", domain: "dropbox.com" },
  { slug: "samsara", name: "Samsara", domain: "samsara.com" },
  { slug: "mongodb", name: "MongoDB", domain: "mongodb.com" },
  { slug: "elastic", name: "Elastic", domain: "elastic.co" },
  { slug: "amplitude", name: "Amplitude", domain: "amplitude.com" },
  { slug: "peloton", name: "Peloton", domain: "onepeloton.com" },
  { slug: "chime", name: "Chime", domain: "chime.com" },
  { slug: "carta", name: "Carta", domain: "carta.com" },
  { slug: "betterment", name: "Betterment", domain: "betterment.com" },
  { slug: "sofi", name: "SoFi", domain: "sofi.com" },
  { slug: "coursera", name: "Coursera", domain: "coursera.org" },
  { slug: "udemy", name: "Udemy", domain: "udemy.com" },
  { slug: "calendly", name: "Calendly", domain: "calendly.com" },
  { slug: "typeform", name: "Typeform", domain: "typeform.com" },
  { slug: "airtable", name: "Airtable", domain: "airtable.com" },
  { slug: "lattice", name: "Lattice", domain: "lattice.com" },
  { slug: "branch", name: "Branch", domain: "branch.io" },
  { slug: "intercom", name: "Intercom", domain: "intercom.com" },
  { slug: "hubspot", name: "HubSpot", domain: "hubspot.com" },
  { slug: "pagerduty", name: "PagerDuty", domain: "pagerduty.com" },
  { slug: "datadog", name: "Datadog", domain: "datadoghq.com" },
  { slug: "newrelic", name: "New Relic", domain: "newrelic.com" },

  // Canadian tech companies
  { slug: "hootsuite", name: "Hootsuite", domain: "hootsuite.com" },
  { slug: "later", name: "Later", domain: "later.com" },
  { slug: "d2l", name: "D2L", domain: "d2l.com" },
  { slug: "auviknetworks", name: "Auvik Networks", domain: "auvik.com" },
  { slug: "unbounce", name: "Unbounce", domain: "unbounce.com" },
  { slug: "flipp", name: "Flipp", domain: "flipp.com" },
  { slug: "goodnotes", name: "GoodNotes", domain: "goodnotes.com" },
  { slug: "ritual", name: "Ritual", domain: "ritual.co" },
  { slug: "faire", name: "Faire", domain: "faire.com" },

  // Devtools / martech / sales
  { slug: "addepar1", name: "Addepar", domain: "addepar.com" },
  { slug: "launchdarkly", name: "LaunchDarkly", domain: "launchdarkly.com" },
  { slug: "pendo", name: "Pendo", domain: "pendo.io" },
  { slug: "salesloft", name: "Salesloft", domain: "salesloft.com" },
  { slug: "apolloio", name: "Apollo.io", domain: "apollo.io" },
  { slug: "6sense", name: "6sense", domain: "6sense.com" },
  { slug: "bombora", name: "Bombora", domain: "bombora.com" },
  { slug: "showpad", name: "Showpad", domain: "showpad.com" },
  { slug: "qualtrics", name: "Qualtrics", domain: "qualtrics.com" },
  { slug: "zoominfo", name: "ZoomInfo", domain: "zoominfo.com" },

  // Health / fintech / fraud & identity
  { slug: "calm", name: "Calm", domain: "calm.com" },
  { slug: "classpass", name: "ClassPass", domain: "classpass.com" },
  { slug: "super", name: "Super.com", domain: "super.com" },
  { slug: "mavenclinic", name: "Maven Clinic", domain: "mavenclinic.com" },
  { slug: "parsleyhealth", name: "Parsley Health", domain: "parsleyhealth.com" },
  { slug: "jumio", name: "Jumio", domain: "jumio.com" },
  { slug: "veriff", name: "Veriff", domain: "veriff.com" },
  { slug: "forter", name: "Forter", domain: "forter.com" },
  { slug: "riskified", name: "Riskified", domain: "riskified.com" },
  { slug: "sezzle", name: "Sezzle", domain: "sezzle.com" },
  { slug: "galileo", name: "Galileo Financial Technologies", domain: "galileo-ft.com" },

  // Aerospace / autonomous vehicles
  { slug: "wayve", name: "Wayve", domain: "wayve.ai" },
  { slug: "kodiak", name: "Kodiak Robotics", domain: "kodiak.ai" },
  { slug: "vardaspace", name: "Varda Space Industries", domain: "varda.com" },
  { slug: "relativity", name: "Relativity Space", domain: "relativityspace.com" },
  { slug: "astranis", name: "Astranis", domain: "astranis.com" },
  { slug: "rocketlab", name: "Rocket Lab", domain: "rocketlabusa.com" },
  { slug: "planetlabs", name: "Planet Labs", domain: "planet.com" },

  // Gaming / crypto
  { slug: "riotgames", name: "Riot Games", domain: "riotgames.com" },
  { slug: "epicgames", name: "Epic Games", domain: "epicgames.com" },
  { slug: "scopely", name: "Scopely", domain: "scopely.com" },
  { slug: "consensys", name: "Consensys", domain: "consensys.io" },
  { slug: "fireblocks", name: "Fireblocks", domain: "fireblocks.com" },
  { slug: "gemini", name: "Gemini", domain: "gemini.com" },

  // Cybersecurity
  { slug: "orcasecurity", name: "Orca Security", domain: "orca.security" },
  { slug: "cribl", name: "Cribl", domain: "cribl.io" },
  { slug: "tanium", name: "Tanium", domain: "tanium.com" },
  { slug: "huntress", name: "Huntress", domain: "huntress.com" },
  { slug: "abnormalsecurity", name: "Abnormal Security", domain: "abnormalsecurity.com" },
  { slug: "wing", name: "Wing Security", domain: "wing.security" },
  { slug: "zscaler", name: "Zscaler", domain: "zscaler.com" },
  { slug: "axiad", name: "Axiad", domain: "axiad.com" },
  { slug: "hypr", name: "HYPR", domain: "hypr.com" },
  { slug: "transmitsecurity", name: "Transmit Security", domain: "transmitsecurity.com" },

  // Edtech / proptech
  { slug: "masterclass", name: "MasterClass", domain: "masterclass.com" },
  { slug: "udacity", name: "Udacity", domain: "udacity.com" },
  { slug: "khanacademy", name: "Khan Academy", domain: "khanacademy.org" },
  { slug: "hometap", name: "Hometap", domain: "hometap.com" },
  { slug: "pointdigitalfinance", name: "Point", domain: "point.com" },
  { slug: "orchard", name: "Orchard", domain: "orchard.com" },
  { slug: "homelight", name: "HomeLight", domain: "homelight.com" },
  { slug: "knock", name: "Knock", domain: "knock.com" },

  // Media / logistics
  { slug: "crunchyroll", name: "Crunchyroll", domain: "crunchyroll.com" },
  { slug: "tubi", name: "Tubi", domain: "tubitv.com" },
  { slug: "fubotv", name: "fuboTV", domain: "fubo.tv" },
  { slug: "philo", name: "Philo", domain: "philo.com" },
  { slug: "fourkites", name: "FourKites", domain: "fourkites.com" },
  { slug: "wolt", name: "Wolt", domain: "wolt.com" },

  // Legal tech / insurtech
  { slug: "coalition", name: "Coalition", domain: "coalitioninc.com" },
  { slug: "resilience", name: "Resilience", domain: "cyberresilience.com" },
  { slug: "thoropass", name: "Thoropass", domain: "thoropass.com" },
  { slug: "laika", name: "Laika", domain: "heylaika.com" },
  { slug: "hyperproof", name: "Hyperproof", domain: "hyperproof.io" },
  { slug: "complyadvantage", name: "ComplyAdvantage", domain: "complyadvantage.com" },

  // Observability / MLOps / AI
  { slug: "honeycomb", name: "Honeycomb", domain: "honeycomb.io" },
  { slug: "axiom", name: "Axiom", domain: "axiom.co" },
  { slug: "comet", name: "Comet", domain: "comet.com" },
  { slug: "gleanwork", name: "Glean", domain: "glean.com" },
  { slug: "descript", name: "Descript", domain: "descript.com" },
  { slug: "otterai", name: "Otter.ai", domain: "otter.ai" },
  { slug: "heygen", name: "HeyGen", domain: "heygen.com" },

  // Global payroll / no-code
  { slug: "globalizationpartners", name: "G-P (Globalization Partners)", domain: "g-p.com" },
  { slug: "glide", name: "Glide", domain: "glideapps.com" },
  { slug: "make", name: "Make", domain: "make.com" },
  { slug: "workato", name: "Workato", domain: "workato.com" },

  // Data infrastructure
  { slug: "hightouch", name: "Hightouch", domain: "hightouch.io" },
  { slug: "fivetran", name: "Fivetran", domain: "fivetran.com" },
  { slug: "cockroachlabs", name: "Cockroach Labs", domain: "cockroachlabs.com" },
  { slug: "yugabyte", name: "Yugabyte", domain: "yugabyte.com" },

  // CMS / customer experience
  { slug: "storyblok", name: "Storyblok", domain: "storyblok.com" },
  { slug: "builder", name: "Builder.io", domain: "builder.io" },
  { slug: "iterable", name: "Iterable", domain: "iterable.com" },
  { slug: "yotpo", name: "Yotpo", domain: "yotpo.com" },
  { slug: "aftership", name: "AfterShip", domain: "aftership.com" },
  { slug: "narvar", name: "Narvar", domain: "narvar.com" },

  // Ecommerce / generative AI
  { slug: "klaviyo", name: "Klaviyo", domain: "klaviyo.com" },
  { slug: "easyship", name: "Easyship", domain: "easyship.com" },
  { slug: "inflectionai", name: "Inflection AI", domain: "inflection.ai" },
  { slug: "imbue", name: "Imbue", domain: "imbue.com" },
  { slug: "udio", name: "Udio", domain: "udio.com" },
  { slug: "stabilityai", name: "Stability AI", domain: "stability.ai" },
  { slug: "assemblyai", name: "AssemblyAI", domain: "assemblyai.com" },
  { slug: "speechmatics", name: "Speechmatics", domain: "speechmatics.com" },
  { slug: "wellsaidlabs", name: "WellSaid Labs", domain: "wellsaidlabs.com" },
  { slug: "anthropic", name: "Anthropic", domain: "anthropic.com" },
  { slug: "postman", name: "Postman", domain: "postman.com" },
  { slug: "netlify", name: "Netlify", domain: "netlify.com" },

  // Infra / manufacturing / hardware
  { slug: "purestorage", name: "Pure Storage", domain: "purestorage.com" },
  { slug: "fastly", name: "Fastly", domain: "fastly.com" },
  { slug: "neo4j", name: "Neo4j", domain: "neo4j.com" },
  { slug: "stackblitz", name: "StackBlitz", domain: "stackblitz.com" },
  { slug: "xometry", name: "Xometry", domain: "xometry.com" },
  { slug: "fictiv", name: "Fictiv", domain: "fictiv.com" },
  { slug: "markforged", name: "Markforged", domain: "markforged.com" },
  { slug: "formlabs", name: "Formlabs", domain: "formlabs.com" },

  // Climate / energy
  { slug: "patch", name: "Patch", domain: "patch.io" },
  { slug: "cloverly", name: "Cloverly", domain: "cloverly.com" },
  { slug: "antora", name: "Antora Energy", domain: "antoraenergy.com" },
  { slug: "sunnova", name: "Sunnova", domain: "sunnova.com" },
  { slug: "ursamajor", name: "Ursa Major", domain: "ursamajor.com" },
  { slug: "wrike", name: "Wrike", domain: "wrike.com" },
  { slug: "smartsheet", name: "Smartsheet", domain: "smartsheet.com" },
  { slug: "upgrade", name: "Upgrade", domain: "upgrade.com" },
  { slug: "earnest", name: "Earnest", domain: "earnest.com" },
  { slug: "gofundme", name: "GoFundMe", domain: "gofundme.com" },
  { slug: "mightynetworks", name: "Mighty Networks", domain: "mightynetworks.com" },
];

export const LEVER_COMPANIES: CompanyConfig[] = [
  { slug: "palantir", name: "Palantir", domain: "palantir.com" },
  { slug: "gopuff", name: "Gopuff", domain: "gopuff.com" },
  { slug: "matchgroup", name: "Match Group", domain: "mtch.com" },
  { slug: "nium", name: "Nium", domain: "nium.com" },
  { slug: "zoox", name: "Zoox", domain: "zoox.com" },
  { slug: "tala", name: "Tala", domain: "tala.co" },
  { slug: "everlywell", name: "Everlywell", domain: "everlywell.com" },
  { slug: "ro", name: "Ro", domain: "ro.co" },
  { slug: "linkedin", name: "LinkedIn", domain: "linkedin.com" },
  { slug: "gettyimages", name: "Getty Images", domain: "gettyimages.com" },
  { slug: "angellist", name: "AngelList", domain: "angellist.com" },
  { slug: "moonpay", name: "MoonPay", domain: "moonpay.com" },
  { slug: "certik", name: "CertiK", domain: "certik.com" },
  { slug: "1inch", name: "1inch", domain: "1inch.io" },
  { slug: "cloudinary", name: "Cloudinary", domain: "cloudinary.com" },
  { slug: "charmindustrial", name: "Charm Industrial", domain: "charmindustrial.com" },
  { slug: "arcadia", name: "Arcadia", domain: "arcadia.com" },
  { slug: "omnisend", name: "Omnisend", domain: "omnisend.com" },
];

export const ASHBY_COMPANIES: CompanyConfig[] = [
  { slug: "notion", name: "Notion", domain: "notion.so" },
  { slug: "linear", name: "Linear", domain: "linear.app" },
  { slug: "ramp", name: "Ramp", domain: "ramp.com" },
  { slug: "openai", name: "OpenAI", domain: "openai.com" },
  { slug: "replit", name: "Replit", domain: "replit.com" },
  { slug: "substack", name: "Substack", domain: "substack.com" },
  { slug: "runway", name: "Runway", domain: "runwayml.com" },
  { slug: "teamworks", name: "Teamworks", domain: "teamworks.com" },
  { slug: "watershed", name: "Watershed", domain: "watershed.com" },
  { slug: "sardine", name: "Sardine", domain: "sardine.ai" },
  { slug: "attio", name: "Attio", domain: "attio.com" },
  { slug: "bland", name: "Bland", domain: "bland.ai" },
  { slug: "harvey", name: "Harvey", domain: "harvey.ai" },
  { slug: "perplexity", name: "Perplexity", domain: "perplexity.ai" },
  { slug: "cohere", name: "Cohere", domain: "cohere.com" },
  { slug: "primer", name: "Primer", domain: "primer.io" },
  { slug: "middesk", name: "Middesk", domain: "middesk.com" },
  { slug: "rutter", name: "Rutter", domain: "rutter.com" },
  { slug: "hex", name: "Hex", domain: "hex.tech" },
  { slug: "temporal", name: "Temporal", domain: "temporal.io" },
  { slug: "warp", name: "Warp", domain: "warp.dev" },
  { slug: "cursor", name: "Cursor", domain: "cursor.com" },
  { slug: "fireworks", name: "Fireworks AI", domain: "fireworks.ai" },
  { slug: "baseten", name: "Baseten", domain: "baseten.co" },
  { slug: "modal", name: "Modal", domain: "modal.com" },
  { slug: "neon", name: "Neon", domain: "neon.tech" },
  { slug: "supabase", name: "Supabase", domain: "supabase.com" },
  { slug: "railway", name: "Railway", domain: "railway.app" },
  { slug: "render", name: "Render", domain: "render.com" },
  { slug: "vanta", name: "Vanta", domain: "vanta.com" },
  { slug: "drata", name: "Drata", domain: "drata.com" },
  { slug: "secureframe", name: "Secureframe", domain: "secureframe.com" },
  { slug: "oneleet", name: "Oneleet", domain: "oneleet.com" },
  { slug: "clerk", name: "Clerk", domain: "clerk.com" },
  { slug: "workos", name: "WorkOS", domain: "workos.com" },
  { slug: "stytch", name: "Stytch", domain: "stytch.com" },
  { slug: "persona", name: "Persona", domain: "withpersona.com" },
  { slug: "unit", name: "Unit", domain: "unit.co" },
  { slug: "astra", name: "Astra", domain: "astra.finance" },
  { slug: "column", name: "Column", domain: "column.com" },
  { slug: "wealthsimple", name: "Wealthsimple", domain: "wealthsimple.com" },
  { slug: "koho", name: "KOHO", domain: "koho.ca" },
  { slug: "neofinancial", name: "Neo Financial", domain: "neofinancial.com" },
  { slug: "nerdwallet", name: "NerdWallet", domain: "nerdwallet.com" },

  // Dev tools / testing
  { slug: "browserbase", name: "Browserbase", domain: "browserbase.com" },
  { slug: "chromatic", name: "Chromatic", domain: "chromatic.com" },
  { slug: "mazedesign", name: "Maze", domain: "maze.co" },
  { slug: "mintlify", name: "Mintlify", domain: "mintlify.com" },
  { slug: "readme", name: "ReadMe", domain: "readme.com" },
  { slug: "gitbook", name: "GitBook", domain: "gitbook.com" },

  // AI infra / applied AI
  { slug: "saronic", name: "Saronic", domain: "saronic.com" },
  { slug: "decagon", name: "Decagon", domain: "decagon.ai" },
  { slug: "sierra", name: "Sierra", domain: "sierra.ai" },
  { slug: "parloa", name: "Parloa", domain: "parloa.com" },
  { slug: "braintrust", name: "Braintrust", domain: "braintrust.dev" },
  { slug: "langchain", name: "LangChain", domain: "langchain.com" },
  { slug: "llamaindex", name: "LlamaIndex", domain: "llamaindex.ai" },
  { slug: "pinecone", name: "Pinecone", domain: "pinecone.io" },
  { slug: "weaviate", name: "Weaviate", domain: "weaviate.io" },
  { slug: "cartesia", name: "Cartesia", domain: "cartesia.ai" },
  { slug: "rime", name: "Rime", domain: "rime.ai" },
  { slug: "opusclip", name: "OpusClip", domain: "opus.pro" },

  // Analytics / comms infra
  { slug: "omni", name: "Omni", domain: "omni.co" },
  { slug: "resend", name: "Resend", domain: "resend.com" },

  // Health tech / legal tech
  { slug: "summerhealth", name: "Summer Health", domain: "summerhealth.com" },
  { slug: "candidhealth", name: "Candid Health", domain: "candidhealth.com" },
  { slug: "akasa", name: "Akasa", domain: "akasa.com" },
  { slug: "legora", name: "Legora", domain: "legora.com" },

  // Fintech / billing / compliance
  { slug: "paradigm", name: "Paradigm", domain: "paradigm.co" },
  { slug: "assured", name: "Assured", domain: "getassured.com" },
  { slug: "clipboard", name: "Clipboard Health", domain: "clipboardhealth.com" },
  { slug: "speak", name: "Speak", domain: "speak.com" },
  { slug: "speakeasy", name: "Speakeasy", domain: "speakeasy.com" },
  { slug: "orb", name: "Orb", domain: "withorb.com" },
  { slug: "lago", name: "Lago", domain: "getlago.com" },
  { slug: "snowflake", name: "Snowflake", domain: "snowflake.com" },
  { slug: "plaid", name: "Plaid", domain: "plaid.com" },
  { slug: "benchling", name: "Benchling", domain: "benchling.com" },
  { slug: "confluent", name: "Confluent", domain: "confluent.io" },
  { slug: "bunny", name: "Bunny", domain: "bunny.net" },
  { slug: "scalar", name: "Scalar", domain: "scalar.com" },
  { slug: "kong", name: "Kong", domain: "konghq.com" },
  { slug: "heirloomcarbon", name: "Heirloom", domain: "heirloomcarbon.com" },
  { slug: "formenergy", name: "Form Energy", domain: "formenergy.com" },
  { slug: "helion", name: "Helion Energy", domain: "helionenergy.com" },
  { slug: "span", name: "Span", domain: "span.io" },
  { slug: "aurorasolar", name: "Aurora Solar", domain: "aurorasolar.com" },
  { slug: "titan", name: "Titan", domain: "titan.com" },
];
